<?php

/**
 * @copyright  2015-2016 Telecom SudParis - Olivier Berger
 * @license    "MIT/X" License - cf. LICENSE file at project root
 */

namespace AppBundle\Repository;

/**
 * ProgrammationCircuitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgrammationCircuitRepository extends \Doctrine\ORM\EntityRepository
{

	/*
	 * Chargement des circuits en même temps que les programmations
	 */
	public function findAllJoinedToCircuit()
	{
		$query = $this->getEntityManager()
			->createQuery(
				'SELECT p, c FROM AppBundle:ProgrammationCircuit p
	            JOIN p.circuit c');
	
		return $query->getResult();
	}

	/*
	 * Chargement du circuit en même temps que la programmation
	 */
	public function findOneByIdJoinedToCircuit($programmationId)
	{
	    $query = $this->getEntityManager()
	        ->createQuery(
	            'SELECT p, c FROM AppBundle:ProgrammationCircuit p
	            JOIN p.circuit c
	            WHERE p.id = :id'
	        )->setParameter('id', $programmationId);
	
	    try {
	        return $query->getSingleResult();
	    } catch (\Doctrine\ORM\NoResultException $e) {
	        return null;
	    }
	}
}
